### PR TITLE
Rename Tenant Operator to Multi Tenant Operator

### PR DESCRIPTION
**Pull request by MahnoorAsghar**
Rename Tenant Operator to Multi Tenant Operator

### CODE REVIEW

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-77-70809950`

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-77-1d0a32a1`

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-77-f616399b`

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-77-38203ff5`

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-77-f65ef676`

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-77-1d643a71`

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-77-ef72c682`

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-77-30fce89a`

**Review by hussnain612 — APPROVED** [review]

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-77-6066eafe`

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:v0.0.52`

**Pull request merged**
