### PR TITLE
update application onboarding guide

### PR DESCRIPTION
**Pull request by rasheedamir**
improve app onboarding steps

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-81-2f9922ea`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-81-a15c1e57`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-81-d14e793d`

**Comment by stakater-user** [comment]
@AsfaMumtaz Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/3b602e58d78615dafebea0bd63416d1df92dcc5f/checks) has Failed!

**Comment by stakater-user** [comment]
@AsfaMumtaz Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-81-df89dfd6`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-81-2e11d05a`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-81-d394bdce`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-81-b5326ffe`

**Comment by stakater-user** [comment]
@mustafaStakater Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-81-81862559`

**Comment by karl-johan-grahn** [comment]
@rasheedamir can we get this green soon so we can review and merge it soon

**Comment by karl-johan-grahn** [comment]
I'll merge this for now once it's green to get doc migration done

**Review by karl-johan-grahn — APPROVED** [review]

**Pull request merged**
