### PR TITLE
Fix spelling errors in MTO Overview page, basic-overview diagram

### PR DESCRIPTION
**Pull request by MahnoorAsghar**
The tenant-operator-basic-overview diagram had 2 spelling errors, which are corrected in this PR:
- TemplatGroupInstance -> TemplateGroupInstance
- OpenSift Resource -> OpenShift Resource (in the Legend)

### CODE REVIEW

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-98-4724e768`

**Review by hussnain612 — APPROVED** [review]

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-98-a09af093`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-98-fc12fec1`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-98-8c69f99a`

**Review by rasheedamir — APPROVED** [review]

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.saap-prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.79`

**Pull request merged**
