### PR TITLE
Release process clouddocs

### PR DESCRIPTION
**Pull request by Muneebstakater**

### CODE REVIEW

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-32-3e2204ad`

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-32-2eb0750b`

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-32-133214da`

**Comment by Muneebstakater** [comment]
Closing this PR

**Pull request closed without merging**
