### PR TITLE
Adds machinepool docs

### PR DESCRIPTION
**Pull request by KhizerJaan**

### CODE REVIEW

**Comment by stakater-user** [comment]
@KhizerJaan Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-83-74c8f2a6`

**Comment by stakater-user** [comment]
@KhizerJaan Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-83-dc21a98e`

**Comment by stakater-user** [comment]
@KhizerJaan Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-83-f02951fa`

**Review by karl-johan-grahn — APPROVED** [review]

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.56`

**Pull request merged**
