### PR TITLE
Tronador - Add info about TronadorConfig supporting orgLevelSecrets 

### PR DESCRIPTION
**Pull request by MahnoorAsghar**
Tronador - Add information about TronadorConfig supporting orgLevelSecrets (default Secrets)

### CODE REVIEW

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-23-83fc8334`

**Review by ShahidHussain-srti — CHANGES_REQUESTED** [review]
add changelog

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-23-f04dd166`

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-23-88f6c24c`

**Review by ShahidHussain-srti — APPROVED** [review]

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.12`

**Pull request merged**
