### PR TITLE
Ehi update to doc 2

### PR DESCRIPTION
**Pull request by MahnoorAsghar**

### CODE REVIEW

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/a246ef5b9cde917b3d2b908ab2856bc23f04477d/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/d965483510f7340d1ba7557300c962c31e8fea30/checks) has Failed!

**Comment by stakater-user** [comment]
@ehienabulele Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/98e2372cf0b0e2a2901385a6cd33b047a993df7b/checks) has Failed!

**Review by ehienabulele — APPROVED** [review]

**Comment by stakater-user** [comment]
@ehienabulele Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit//checks) has Failed!

**Pull request merged**
