### PR TITLE
Update registry

### PR DESCRIPTION
**Pull request by karl-johan-grahn**
Docker image registry update

### CODE REVIEW

**Comment by stakater-user** [comment]
@karl-johan-grahn Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/5a98af279acc425757b543826581ec1270c5f30d/checks) has Failed!

**Comment by stakater-user** [comment]
@karl-johan-grahn Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/461c075e5b8b24de7d605ae1cd1e637a6fef1812/checks) has Failed!

**Comment by stakater-user** [comment]
@karl-johan-grahn Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/c79a73c47db0a1cd02938ff5dd28c400f6e297fe/checks) has Failed!

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-75-c79a73c4`

**Review by callum-stakater — APPROVED** [review]

**Comment by stakater-user** [comment]
@karl-johan-grahn Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:v0.0.49`

**Pull request merged**
