### PR TITLE
create saap-vs-k8s

### PR DESCRIPTION
**Pull request by rasheedamir**
saap-vs-k8s

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-30-7aab4d57`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-30-30c6b2cc`

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-30-7cd402b7`

**Review by Muneebstakater — APPROVED** [review]

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.13`

**Pull request merged**
