### PR TITLE
Update TO Overview page

### PR DESCRIPTION
**Pull request by MahnoorAsghar**

### CODE REVIEW

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/337a4308ae632253df59f6647e8d965cbc8e98df/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/47883545b4f776742ee193e5c98f1157323382ea/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/584414f8f3b126e69089de68b00c36fff10c377a/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/48e62ce1ac911d14802ec711e3328f78a4048ac8/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-48-f63e1782`

**Review by abdulhaseeb2 — APPROVED** [review]

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.29`

**Pull request merged**
