### PR TITLE
[tenant-operator] Add new use case for Sealed Secrets in templates

### PR DESCRIPTION
**Pull request by MuneebAijaz**

### CODE REVIEW

**Comment by stakater-user** [comment]
@MuneebAijaz Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/4247d0a52a8e1152325577285b9813b4b0389c74/checks) has Failed!

**Comment by stakater-user** [comment]
@MuneebAijaz Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-33-d5ac220b`

**Comment by stakater-user** [comment]
@MuneebAijaz Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-33-69ae5924`

**Review by tanalam2411 — APPROVED** [review]

**Comment by stakater-user** [comment]
@MuneebAijaz Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.15`

**Pull request merged**
