### PR TITLE
Update TO Vault multitenancy page

### PR DESCRIPTION
**Pull request by MahnoorAsghar**
Improve description
Improve diagram

### CODE REVIEW

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/9eab578ebb92991773c0561b91e9ebbc6f5afc7a/checks) has Failed!

**Comment by stakater-user** [comment]
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-47-c05951ca`

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/c3e92a83adf5227088480711925c60a2a9b75440/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/07abd3a9f391f343ca3ba4bbb4f2da27c7af5f91/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/a918dd88440324949233d32478b4722868c430d8/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/StakaterCloudDocs/commit/f3b2046748fe913c469cc5cdd6e11534aea2dd95/checks) has Failed!

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:SNAPSHOT-PR-47-89434977`

**Review by hussnain612 — APPROVED** [review]

**Review by abdulhaseeb2 — APPROVED** [review]

**Comment by stakater-user** [comment]
@MahnoorAsghar Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.28`

**Pull request merged**
