### PR TITLE
[MAN-1] update images

### PR DESCRIPTION
**Pull request by rasheedamir**
updated images

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-105-1c536434`

**Review by abaziz — DISMISSED** [review]

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-105-78bbaf2c`

**Review by abaziz — DISMISSED** [review]

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.preprod.jlvwjls8.kubeapp.cloud/stakater/stakaterclouddocs:SNAPSHOT-PR-105-b5ae1d08`

**Review by ShahidHussain-srti — APPROVED** [review]

**Comment by stakater-user** [comment]
@rasheedamir Image is available for testing. `docker pull nexus-docker-stakater-nexus.apps.saap-prod.clusters.stakater.io/stakater/stakaterclouddocs:v0.0.78`

**Pull request merged**
